export const PROFILES = {
  SUPER_ADMIN: 1,
  ADMIN: 2,
  EMPRESA: 3,
  SUPERVISOR: 4,
  VENDEDOR: 5,
}

export const PRODUCT_TYPE = {
  DIGITAL: 'DIGITAL',
  FISICO: 'FISICO',
}

export const STATUS = {
  ATIVO: 'ATIVO',
  INATIVO: 'INATIVO'
}

export const LINKS =  {
  DISCOUNT: 'DISCOUNT',
  CHECKOUT: 'CHECKOUT'
}

export const MIDIAS_TYPES = {
  THUMBNAIL: 'THUMBNAIL',
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  EBOOK: 'EBOOK',
}